{{- if .Values.kafka.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data
  labels:
    app: kafka
    component: messaging
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.kafka.persistence.size }}
  {{- if .Values.kafka.persistence.storageClass }}
  storageClassName: {{ .Values.kafka.persistence.storageClass }}
  {{- end }}
{{- end }}