apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
    component: messaging
spec:
  type: ClusterIP
  ports:
  - name: kafka
    port: {{ .Values.kafka.service.port }}
    targetPort: kafka
    protocol: TCP
  - name: controller
    port: 9093
    targetPort: controller
    protocol: TCP
  selector:
    app: kafka