

on: 
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          url: ${{ secrets.OKTETO_CONTEXT }}

      - name: Deploy preview environment
        uses: okteto/deploy-preview@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: pr-${{ github.event.number }}-cindylopez
          scope: global